name: Build Sphinx Docker Image

on:
  push:
    #tags:
    #  - "**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: .Dockerfile
            image: |
              ${{ github.repository }}:latest
              ${{ github.repository }}:${{ github.ref_name }}
              ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
              ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}
          - dockerfile: .Dockerfile_pdf
            image: |
              ${{ github.repository }}_pdf:latest
              ${{ github.repository }}_pdf:${{ github.ref_name }}
              ghcr.io/${{ github.actor }}/${{ github.repository }}_pdf:latest
              ghcr.io/${{ github.actor }}/${{ github.repository }}_pdf:${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref_name == 'v*' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .devcontainer/
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          tags:  ${{ matrix.image }}
          labels: ${{ matrix.image }}
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
